# Two pods, one container each
# Each container asking for 1 distinct GPU

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  namespace: rt3
  name: rta.example.com
spec:
  spec:
    resourceClassName: rt.example.com
    parametersRef:
      apiGroup: rt.resource.example.com
      kind: RtClaimParameters
      name: rtclaims-a
---
apiVersion: resource.k8s.io/v1alpha2
kind: RtClaimParameters
metadata:
  namespace: rt3
  name: rtclaims-a
spec:
  count: 4
  runtime: 1000
  period: 1000000
---
apiVersion: rt.resource.example.com/v1alpha1
kind: RtClaimParameters
metadata:
  namespace: rt3
  name: rt.example.com
spec:
  spec:
    resourceClassName: rt.example.com
    parametersRef:
      apiGroup: rt.resource.example.com
      kind: RtClaimParameters
      name: rtclaims-b
---
apiVersion: rt.resource.example.com/v1alpha1
kind: RtClaimParameters
metadata:
  namespace: rt3
  name: rtclaims-b
spec:
  count: 4
  runtime: 2000
  period: 3000000

---
apiVersion: v1
kind: Pod
metadata:
  namespace: rt3
  name: pod0
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; sleep 9999"]
    resources:
      claims:
      - name: rtcpu-a
  resourceClaims:
  - name: rtcpu-a
    source:
      resourceClaimTemplateName: rt.example.com
---
apiVersion: v1
kind: Pod
metadata:
  namespace: rt3
  name: pod1
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; sleep 9999"]
    resources:
      claims:
      - name: rtcpu-b
  resourceClaims:
  - name: rtcpu-b
    source:
      resourceClaimTemplateName: rt.example.com

---