# Two pods, one container each                                                                                                                                                                                                                                                
# Each container asking for 1 distinct cpu                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                
---                                                                                                                                                                                                                                                                           
apiVersion: v1                                                                                                                                                                                                                                                                
kind: Namespace                                                                                                                                                                                                                                                               
metadata:                                                                                                                                                                                                                                                                     
  name: rt-test1                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                
---                                                                                                                                                                                                                                                                           
apiVersion: rt.resource.example.com/v1alpha1
kind: RtClaimParameters
metadata:
  namespace: rt-test1
  name: rtclaims0
spec:
  count: 1
  runtime: 100
  period: 1000
  requestedCpus: [1]

---           
apiVersion: rt.resource.example.com/v1alpha1
kind: RtClaimParameters
metadata:
  namespace: rt-test1
  name: rtclaims1
spec:
  count: 1
  runtime: 100
  period: 1000
  requestedCpus: [2]

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  namespace: rt-test1
  name: rt-claim-template0
spec:
  spec:
    resourceClassName: rt.example.com
    parametersRef:
      apiGroup: rt.resource.example.com
      kind: RtClaimParameters
      name: rtclaims0

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate  
spec:
  spec: 
    resourceClassName: rt.example.com
    parametersRef:
      apiGroup: rt.resource.example.com
      kind: RtClaimParameters
      name: rtclaims1
      
---   
apiVersion: v1
kind: Pod
metadata:
  namespace: rt-test1                  
  name: pod0
  labels: { app: pod }
spec:
  tolerations: [{ operator: Exists }]
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; sleep 9999"]
    resources:
      claims:
      - name: rtcpu
  resourceClaims:
  - name: rtcpu
    source:
      resourceClaimTemplateName: rt-claim-template0

---
apiVersion: v1
kind: Pod
metadata:
  namespace: rt-test1
  name: pod1
  labels: { app: pod }
spec:
  tolerations: [{ operator: Exists }]
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; sleep 9999"]
    resources:
      claims:
      - name: rtcpu
  resourceClaims:
  - name: rtcpu
    source:
      resourceClaimTemplateName: rt-claim-template1   